### ISSUE TITLE
Error when using stylus on Windows

### ISSUE THREAD

**Issue by stela5** [dmnsgn/gulp-frontend-boilerplate#11]
When selecting stylus support on Windows (node v4), it fails with the following trace (running in a Windows command prompt launched with admin privileges):

```
? CSS preprocessor: Stylus
Adding babelify transform(s) to package.json.
Installing dependencies and adding them to package.json... styl-easing styl-font-face babelify gulp-styl
styl-font-face@1.0.1 node_modules\styl-font-face
gulp-styl@1.0.3 node_modules\gulp-styl
+-- through2@0.6.5 (xtend@4.0.0, readable-stream@1.0.33)
+-- styl@0.2.9 (stdin@0.0.1, css-whitespace@1.1.1, rework-mixins@1.1.1, debug@2.2.0, commander@1.1.1, rework@0.18.3)
+-- gulp-util@3.0.6 (array-differ@1.0.0, array-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, object-assign@3.0.0, beeper@1.1.0, l
odash._reescape@3.0.0, replace-ext@0.0.1, minimist@1.2.0, vinyl@0.5.3, lodash.template@3.6.2, through2@2.0.0, multipipe@0.1.2, dateformat@1.0.11)
+-- lodash@3.10.1

babelify@6.3.0 node_modules\babelify
+-- object-assign@3.0.0
+-- babel-core@5.8.25 (try-resolve@1.0.1, slash@1.0.0, babel-plugin-remove-console@1.0.1, babel-plugin-property-literals@1.0.1, babel-plugin-remove-de
bugger@1.0.1, babel-plugin-eval@1.0.1, babel-plugin-inline-environment-variables@1.0.1, babel-plugin-jscript@1.0.4, babel-plugin-react-constant-elemen
ts@1.0.3, babel-plugin-member-expression-literals@1.0.1, babel-plugin-undefined-to-void@1.1.6, babel-plugin-react-display-name@1.0.3, shebang-regex@1.
0.0, path-exists@1.0.0, to-fast-properties@1.0.1, trim-right@1.0.1, path-is-absolute@1.0.0, babel-plugin-constant-folding@1.0.1, fs-readdir-recursive@
0.1.2, babel-plugin-proto-to-assign@1.0.4, babel-plugin-dead-code-elimination@1.0.2, babel-plugin-runtime@1.0.7, private@0.1.6, globals@6.4.1, esutils
@2.0.2, convert-source-map@1.1.1, babel-plugin-undeclared-variables-check@1.0.2, home-or-tmp@1.0.0, js-tokens@1.0.1, line-numbers@0.2.0, is-integer@1.
0.6, debug@2.2.0, repeating@1.1.3, detect-indent@3.0.1, minimatch@2.0.10, babylon@5.8.23, source-map@0.4.4, output-file-sync@1.1.1, resolve@1.1.6, blu
ebird@2.10.2, json5@0.4.0, source-map-support@0.2.10, regexpu@1.3.0, regenerator@0.8.35, lodash@3.10.1, core-js@1.2.1)

> optipng-bin@3.0.2 postinstall c:\tmp\gulp-frontend-boilerplate\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-optipng\node_m
odules\optipng-bin
> node lib/install.js


> gifsicle@3.0.1 postinstall c:\tmp\gulp-frontend-boilerplate\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\imagemin-gifsicle\node_mod
ules\gifsicle
> node lib/install.js


{ [Error: Command failed: C:\Windows\system32\cmd.exe /s /c "npm install --savestyl-easing styl-font-face && npm install --save-dev babelify gulp-styl
 && npm install"
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN optional dep failed, continuing fsevents@1.0.2
npm WARN optional dep failed, continuing imagemin-jpegtran@4.3.0
module.js:338
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\tmp\gulp-frontend-boilerplate\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\buffer-to-vinyl\node_modules
\readable-stream\lib\_stream_duplex.js:20:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
module.js:338
    throw err;
    ^

Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (c:\tmp\gulp-frontend-boilerplate\node_modules\gulp-imagemin\node_modules\imagemin\node_modules\buffer-to-vinyl\node_modules
\readable-stream\lib\_stream_duplex.js:20:23)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\myusername\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! path C:\Users\myusername\AppData\Roaming\npm-cache\longest\1.0.1\package\package.json.72e5ec49f2a9f4ba0d1abeffa848b071
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename

npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\myusername\AppData\Roaming\npm-cache\longest\1.0.1\package\package.json.72e5ec49f2a9f4ba0
d1abeffa848b071' -> 'C:\Users\myusername\AppData\Roaming\npm-cache\longest\1.0.1\package\package.json'
npm ERR!     at Error (native)
npm ERR!  { [Error: EPERM: operation not permitted, rename 'C:\Users\myusername\AppData\Roaming\npm-cache\longest\1.0.1\package\package.json.72e5ec49f2a9f
4ba0d1abeffa848b071' -> 'C:\Users\myusername\AppData\Roaming\npm-cache\longest\1.0.1\package\package.json']
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\myusername\\AppData\\Roaming\\npm-cache\\longest\\1.0.1\\package\\package.json.72e5ec49f2a9f4ba0d1abeffa848b071',
npm ERR!   dest: 'C:\\Users\\myusername\\AppData\\Roaming\\npm-cache\\longest\\1.0.1\\package\\package.json',
npm ERR!   parent: 'browser-sync' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\tmp\gulp-frontend-boilerplate\npm-debug.log
]
  killed: false,
  code: 4294963248,
  signal: null,
  cmd: 'C:\\Windows\\system32\\cmd.exe /s /c "npm install --savestyl-easing styl-font-face && npm install --save-dev babelify gulp-styl && npm install
"' }
```

**Comment by dmnsgn** [comment]
Fixed by a6849865a091b5e09540bf06305f06cb5c8cba7b

Whitespace was missing after --save
```
npm install --save styl-easing styl-font-face && npm install --save-dev babelify gulp-styl
 && npm install
```
